/**created by panchong on 2018/2/23**/
export const ADD_ELEMENTS = 'ADD_ELEMENTS';
export const DELETE_ELEMENTS = 'DELETE_ELEMENTS';
export const CHANGE_FOCUS = 'CHANGE_FOCUS';
export const CHANGE_STYLE = 'CHANGE_STYLE';
export const SET_TOP = 'SET_TOP';
export const SET_BOTTOM = 'SET_BOTTOM';
export const CHANGE_TEXT_EDITABLE = 'CHANGE_TEXT_EDITABLE';
export const CHANGE_TEXT_CONTENT = 'CHANGE_TEXT_CONTENT';
export const CHANGE_IMAGE_SRC = 'CHANGE_IMAGE_SRC';